language: node_js
node_js:
  - "6.0"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false

script:
  - npm test

notifications:
  email: false